# version: '3.9'
services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/:/etc/traefik/
    networks:
      - supabase
    environment:
      CF_DNS_API_TOKEN: YOUR-TOKEN-FROM-CLOUDFLARE
      CLOUDFLARE_EMAIL: YOU-EMAIL-FROM-CLOUDFLARE@gmail.com
      DOMAIN: YOUR-DOMAIN.com
    restart: unless-stopped
    depends_on:
      - dockersocket
      
  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - supabase
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped

networks:
  supabase:
    driver: bridge
    external: true
