http:
  routers:
    ###############################################################################################################################################################################

    ## EXTERNAL ROUTING ##
    traefik:
      entryPoints:
        - https
      rule: "Host(`traefik.YOUR-DOMAIN.com`)"
      service: traefik
      middlewares:
        - "auth"
        - "securityHeaders"
      tls:
        certResolver: letsencrypt

    # Supabase Kong routing
    supabase-kong:
      entryPoints:
        - https
      rule: "Host(`studio.YOUR-DOMAIN.com`)"
      service: supabase-kong
      middlewares:
        - "securityHeaders"
      tls:
        certResolver: letsencrypt        

    # Supabase Analytics routing
    supabase-analytics:
      entryPoints:
        - https
      rule: "Host(`analytics.YOUR-DOMAIN.com`)"
      service: supabase-analytics
      middlewares:
        - "auth"
        - "securityHeaders"
      tls:
        certResolver: letsencrypt        

########################################################################################################################################################################

  ## SERVICES ##
  services:
    # Traefik service
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080

    # Supabase Kong service
    supabase-kong:
      loadBalancer:
        servers:
          - url: "http://kong:8000"

    # Supabase Analytics service
    supabase-analytics:
      loadBalancer:
        servers:
          - url: "http://analytics:4000"

  ###############################################################################################################################################################################

  ## MIDDLEWARES ##
  middlewares:
    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    auth:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd
